# Read the documentation: https://fosrestbundle.readthedocs.io/en/3.x/
fos_rest:
    format_listener:
        rules:
           - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    routing_loader: false

    # L'écouteur du corps de la requête permet de décoder le contenu d'une requête afin 
    # de remplir le sac de paramètres "request" de la requête
    body_listener:
        # e. Si vous souhaitez que l'écouteur de corps transforme les touches soulignées en touches à casse camel,
        #  vous pouvez utiliser le camel_keysnormalisateur
        array_normalizer: fos_rest.normalizer.camel_keys
        

    # mise en place de la configuraion de serializer personélisé
    service:
        # serializer: fos_rest.serializer.jms
        serializer: jms_camel_case
        
    # pour activer le listener du view au moment du return
    view:
        formats: { json: true, xml: false, rss: false }
        view_response_listener: true
    
    body_converter:
        enabled: true

    # ENCORE en attente de confirmation
    # ENCORE en attente de confirmation

#    param_fetcher_listener:  true
#    allowed_methods_listener:  true





#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
